# Generated by Django 5.2.7 on 2025-10-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("share_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("num_shares", models.DecimalField(decimal_places=5, max_digits=6)),
                ("gain_loss", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "action_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculator.action",
                    ),
                ),
                (
                    "asset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.asset",
                    ),
                ),
            ],
        ),
    ]
