# Generated by Django 5.2.7 on 2025-10-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="gain_loss",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="num_shares",
        ),
    ]
