# Generated by Django 5.2.7 on 2025-10-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_remove_transaction_gain_loss_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="purchase_amount",
            new_name="amount",
        ),
    ]
