# Generated by Django 5.2.7 on 2025-10-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_rename_purchase_amount_transaction_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="action_id",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="asset_id",
            new_name="asset",
        ),
    ]
