# Generated by Django 5.2.7 on 2025-10-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_rename_action_id_transaction_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
