# Generated by Django 5.2.7 on 2025-10-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_transaction_is_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="share_price",
        ),
        migrations.AddField(
            model_name="transaction",
            name="share_quantity",
            field=models.DecimalField(decimal_places=5, default=1.56, max_digits=7),
        ),
    ]
