# Generated by Django 5.2.7 on 2025-10-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_remove_transaction_share_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="is_sold",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
